# Generated by Django 3.0.8 on 2020-07-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200727_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default=1, max_length=100, verbose_name='Local do Evento'),
            preserve_default=False,
        ),
    ]
